import {
  WanButton,
  WanButtonGroup,
  WanIcon,
  WanCollapse,
  WanCollapseItem,
  WanAlert,
  WanTooltip,
  WanPopconfirm,
  WanDropdown,
  WanDropdownItem,
  WanConfigProvider,
  WanMessage,
  WanNotification,
  WanInput,
  WanMessageBox,
  WanLoading,
  WanSwitch,
} from "@wan-element/components";
import type { Plugin } from "vue";
export default [
  WanButton,
  WanButtonGroup,
  WanIcon,
  WanCollapse,
  WanCollapseItem,
  WanAlert,
  WanTooltip,
  WanPopconfirm,
  WanDropdown,
  WanDropdownItem,
  WanConfigProvider,
  WanMessage,
  WanNotification,
  WanInput,
  WanMessageBox,
  WanLoading,
  WanSwitch,
] as Plugin[];
